apiVersion: v1
kind: Namespace
metadata:
  name: ns-sub-2
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-ch2
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: nginx-app-details
  name: nginx-app-3
  namespace: ns-sub-2
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: nginx-app-details
status: {}
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: towhichcluster
  namespace: ns-sub-2
spec:
  clusterSelector: {}
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: predev-ch2
  namespace: ns-ch2
  labels:
    app: nginx-app-details
spec:
  type: HelmRepo
  pathname: https://kubernetes-charts.storage.googleapis.com/
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: nginx
  namespace: ns-sub-2
  labels:
    app: nginx-app-details
spec:
  channel: ns-ch2/predev-ch2
  name: nginx-ingress
  packageFilter:
    version: "1.20.x"
  placement:
    placementRef:
      kind: PlacementRule
      name: towhichcluster
---
apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata:
  annotations:
    apps.open-cluster-management.io/is-local-deployable: "false"
  labels:
    app: nginx-app-details
  name: example-configmap
  namespace: ns-sub-2
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: config1
      namespace: default
    data:
      purpose: for test
